services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=loatrack'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'

# docker run -itd -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=1234 -p 5432:5432 -v ./postgres:/var/lib/postgresql/data --name postgresql postgres